### ISSUE TITLE
怎么彻底删除啊，找不到安装目录呢

### ISSUE THREAD

**Issue by jinshenganyuci** [hellodk34/lsky-pro-docker#1]
/path/to/mount/lsky-pro-data这个目录完全找不到

**Comment by hellodk34** [comment]
这个是你宿主机的目录啊，你要自定义一个。

path to mount 的意思就是你自己找一个路径挂载 lsky-pro-data 这个目录。怎么彻底删除？删除容器、删除镜像、删除已挂载的卷或者文件夹。

**Comment by hellodk34** [comment]
解决了吗，解决了我就关 issue 了。
