### ISSUE TITLE
镜像获取完成后无法使用

### ISSUE THREAD

**Issue by haveCodeForCode** [hellodk34/lsky-pro-docker#2]
镜像搭建完成后，点击首页直接就是500，无法使用，是需要反向代理么

**Comment by hellodk34** [comment]
进入首页 500 错误是服务没有正常起来，不是反向代理的问题。有 docker 容器日志吗，可以贴上来看看。

**Comment by hellodk34** [comment]
@haveCodeForCode  找到原因了吗
