### ISSUE TITLE
我在使用这个Nginx配置的时候，出现错误ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by BaeKey** [hellodk34/lsky-pro-docker#4]
百度了一下，问题出在 443端口哪里

修改配置文件，加上ssl问题解决

```
server {
    listen 443 ssl;
```

**Comment by hellodk34** [comment]
可以，一般写成 `listen 443 ssl http2` 更加主流，通用。

**Comment by BaeKey** [comment]
> 可以，一般写成 `listen 443 ssl http2` 更加主流，通用。

知道了，今天才发现下面还有一个http2，百度了一下才知道，确实加上更好

**Comment by hellodk34** [comment]
@BaeKey 感谢提醒，我把 README.md 更新了一下，谢谢。
