### ISSUE TITLE
关于docker部署兰空图床

### ISSUE THREAD

**Issue by OSNewbie** [hellodk34/lsky-pro-docker#5]
出现了安装界面，但是就是创建数据库报错怎么办？

**Comment by OSNewbie** [comment]
只有一个图床的容器，没有一个数据库的容器怎么创建？没有配置数据库的容器，导致数据库创建失败

**Comment by hellodk34** [comment]
**镜像使用**

举一个连接 mysql8 的例子，你也可以使用其他数据库

```
docker network create lsky-pro-net

docker run -d -p 3306:3306 --name mysql8.0.29 --network lsky-pro-net --network-alias mysql --restart=always -e MYSQL_ROOT_PASSWORD=123456 mysql:8.0.29-debian

docker run -d --name=lsky-pro --restart=always --network lsky-pro-net -v /path/to/lsky-pro-data:/var/www/html -p 7791:80 dko0/lsky-pro:2.0.4

docker exec -it mysql8.0.29 bash

mysql -uroot -p123456

create user 'lskypro'@'%' identified by '123456';

grant all privileges on *.* to 'lskypro'@'%' with grant option;

flush privileges;

create database lskypro;
```

浏览器访问 http://your_ip:7791 ，连接数据库时填写上面指定的 host（mysql 容器的名字或者 network-alias 的名字均可）、port（容器内部端口，并非映射的宿主机端口，一般都是 3306）、username（使用专门创建的 lskypro 用户，一般不用 root，最小权限原则）、password（为 lskypro 用户设置的密码）、database_name（数据库名称，lskypro） 再安装即可。

如上，我构建的镜像只有兰空图床服务，数据库要由自己解决的，因为兰空支持多种数据库，mysql、sqlite、postgres 等，所以我就没写。

你可以参考我上面的一些命令自己创建一个 mysql 容器，最好创建一个单独的 lsky-pro-network，将兰空图床和 mysql 的容器都加入到这个 docker network 中，在安装的过程中就可以填写 mysql 的 host、port、username、password、database_name 这些信息了。

我没有用 docker compose 是希望这个 mysql 容器还为其他的应用服务，喜欢 compose 的话就按照 compose 语法编排一下吧。
