### ISSUE TITLE
升级到 v2.1

### ISSUE THREAD

**Issue by hexsix** [hellodk34/lsky-pro-docker#6]
不知道您是否有空将 dockerhub 中的镜像更新到 v2.1 👀

**Comment by hellodk34** [comment]
可以，我周末看看。但是我寻思可以直接在应用内更新就没管了。

**Comment by hexsix** [comment]
> 可以，我周末看看。但是我寻思可以直接在应用内更新就没管了。

@hellodk34 容器内更新的话 compose down up 一下不就白更新了嘛。

**Comment by hellodk34** [comment]
@hexsix  不能 compose down 呀，down 就彻底删除了容器和网络，如果没有挂载卷的话数据就没了。我说的应用内更新是兰空图床设置里的更新，可以在线更新的。

**Comment by hellodk34** [comment]
https://hub.docker.com/r/dko0/lsky-pro/tags

docker pull dko0/lsky-pro:2.1

升级了。
