### ISSUE TITLE
arm 镜像无pgsql驱动,使用redis报错

### ISSUE THREAD

**Issue by lixingbu-tal** [hellodk34/lsky-pro-docker#7]
arm 镜像没有安装pgsql驱动,使用redis报错. 
此外,镜像内含有双份PHP源文件,建议通过docker多阶段形式构建镜像
如果可以,麻烦更新以下镜像

![image](https://user-images.githubusercontent.com/110237853/227535252-3bf96a86-0687-40a9-ba0b-782de5116c3e.png)

**Comment by hellodk34** [comment]
看此 issue ，有如何安装 pg 驱动的说明： https://github.com/hellodk34/lsky-pro-docker/issues/8
