### ISSUE TITLE
容器镜像似乎有问题

### ISSUE THREAD

**Issue by a775566233** [hellodk34/lsky-pro-docker#9]
docker-compose.yml文件
version: '3.1'

services:

  lsky-pro:
    image: dko0/lsky-pro
    restart: always
    ports:
      - 8044:80
    volumes:
      - /home/lsky-pro:/var/www/html

docker-compose日志

lsky-pro_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.2. Set the 'ServerName' directive globally to suppress this message
lsky-pro_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.2. Set the 'ServerName' directive globally to suppress this message
lsky-pro_1  | [Wed May 03 02:30:44.017071 2023] [mpm_prefork:notice] [pid 10] AH00163: Apache/2.4.54 (Debian) PHP/8.1.13 configured -- resuming normal operations
lsky-pro_1  | [Wed May 03 02:30:44.018071 2023] [core:notice] [pid 10] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
^Z

这应该是最新的镜像吧?

**Comment by hellodk34** [comment]
通过 docker-compose.yml 指定 image 为 `dko0/lsky-pro` 肯定是没问题的，如果不指定 tag，默认会请求 latest 的 tag。

但是从你的报错日志来看，不是【最新的镜像？】这个问题。报错日志反映出来的问题大概是 lsky-pro 的配置不对。
